### ISSUE TITLE
MGRS and USNG Northings (and Eastings?) are truncated if 5 digits has leading zeros

### ISSUE THREAD

**Issue by JSibbald** [Esri/coordinate-tool-addin-dotnet#24]
![truncated northing 01](https://cloud.githubusercontent.com/assets/9469350/11508707/158ff3ae-9852-11e5-883b-1933054578e6.png)
![truncated northing 02](https://cloud.githubusercontent.com/assets/9469350/11508706/158e9e82-9852-11e5-8d05-7d4c6efb67b4.png)
When the Northing (and Easting?) 5 digit has a leading zeros then it fails to put in the 5 digits 
For instance using 51.412979931379638 0.0057022423779276915 the returned MGRS is missing the 4 leading zeros in the Northings

![truncated northing 03](https://cloud.githubusercontent.com/assets/9469350/11508886/f3ad06ea-9852-11e5-8c4b-025fd431528f.png)

**Comment by mcalamito** [comment]
This was immediately noticed by the customer when demoed on-site on 18FEB2016. However, the analyst noticed this when he explored the "Expand" button in the output coordinate format. If the Easting or Northing starts with a 0, it is dropped from the expanded results. This cannot be truncated or dropped.

Could this have to do with the text box being an integer instead of a string?

**Comment by topowright** [comment]
@jmccausland I think that there was more to this bug that initially thought.

**Comment by jmccausland** [comment]
@topowright @mcalamito fix has been merged, we need to review and verify

**Comment by mcalamito** [comment]
@jmccausland @topowright I've been able to test and get double and triple 0's to begin my Easting. It does not truncate anymore. Copies out fine as well. Looks fixed to me.

**Comment by topowright** [comment]
This issue can be broken into two pieces: 

1. The issue that was identified by @JSibbald was an issue that can be addressed with formatting. 

2. We have addressed and fixed issues with coordinates that lead with zero that was identified by @mcalamito
