### ISSUE TITLE
Address Lookup - geocode and reverse geocode 

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/coordinate-tool-addin-dotnet#571]
A DOJ customer has requested to have an Address field within coordinate conversion widget. 

- An address could be entered and the appropriate coordinates would be returned. 
- A coordinate could be entered and a reverse geocode is calculated to determine nearest address
- User can click on the map to receive coordinates as well as a reverse geocode of the nearest address

**Comment by dfoll** [comment]
Pre-dev thoughts ideas

`- An address could be entered and the appropriate coordinates would be returned. 
- A coordinate could be entered and a reverse geocode is calculated to determine nearest address
- User can click on the map to receive coordinates as well as a reverse geocode of the nearest address`

1. Missing from ootb functionality, is the ability to have the coordinate returned (address is located, but no coordinate given)
2. Missing from ootb functionality is the ability to have nearest address returned (coordinate is located, but no address given)
3. MIssing from ootb functionality is the ability to return nearest address (address is not returned)

**Comment by dfoll** [comment]
@lfunkhouser i would like to talk about this one ... two questions .... should we move this to the widgets repo? do we also want to add this functionality to the add-in
