### ISSUE TITLE
Consider Batch Coordinate Notation Conversion

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/coordinate-tool-addin-dotnet#6]
Currently the "Convert Coordinate Notation" tool does batch conversion for tables or feature classes.  This new add-in is much more dynamic and a batch conversion that follows the user experience of this new add-in should be considered.  From a user perspective:  How would I best convert a list of twenty target coordinates that I received in an email?

**Comment by topowright** [comment]
This tool will not address batch conversion.
