### ISSUE TITLE
Create Ability to Have Custom Name for Each Coordinate Format in CT Widget

### ISSUE THREAD

**Issue by mcalamito** [Esri/coordinate-tool-addin-dotnet#64]
If we are giving the user the ability to add multiple Coordinate Outputs of the same Coordinate Type, we should add the ability to have a custom name. Otherwise, there is not much of a use case. Why? If I add two DD Coordinates, and I customize one of them, the both DD coordinates update. Therefore, there is no unique benefit to having multiple coordinate outputs of the same type unless we can make each of them unique.

**Comment by MarkTorrey** [comment]
Moving this to widgets [repo](https://github.com/Esri/solutions-webappbuilder-widgets/issues/429)
