### ISSUE TITLE
Sample text not dynamically updating when altered in Advanced options for New Output Coordinate

### ISSUE THREAD

**Issue by BrandonArmstrong** [Esri/coordinate-tool-addin-dotnet#649]
### Issue

When modifying the format for a **New Output Coordinate** via **Advanced** options, the Sample  text is not dynamically updated to reflect the modified format.

### Expected Behavior

The Sample text should be dynamically updated, as outlined in the documentation linked below

[Customize a coordinate format](https://solutions.arcgis.com/defense/help/coordinate-conversion/workflows/customize-a-coordinate-format.htm)
![Sample_text](https://user-images.githubusercontent.com/6314443/76131661-370c4080-5fc4-11ea-96d3-708403e3ab2d.PNG)

This is demonstrated as working properly in a Video for the Coordinate Conversion add-in (ArcMap), found here https://solutions.arcgis.com/defense/help/coordinate-conversion/

### Detailed steps

ArcGIS Pro 2.6 build 23544
Coordinate Conversion Add-In Version and Date: 4.4.2.182 12/2/2019

1. Click the **Add** button in the **Output** section.
    The **Add New Output Coordinate** window appears.

2. Click a coordinate type from the **Category** list.

3. Click the drop-down arrow to expand the **Advanced** dialog.

4. In the **Advanced** dialog, insert or delete characters or spaces to change the way the coordinate is displayed. The Sample text in the dialog **should** show the changes as they are made.

**Comment by lfunkhouser** [comment]
The Coordinate Conversion tool in now released with Pro 2.6. No further Pro development will be managed in this repo. This issue is currently in the near-term plan to be addressed.
