### ISSUE TITLE
Coordinate Tool addin - custom format with DMS does not work with dashes.

### ISSUE THREAD

**Issue by pshowalter** [Esri/coordinate-tool-addin-dotnet#65]
Installed Add-in 2/5 9:30 AM est.

Format string:
**A0:B0:C0.0/X0:Y0:Z0.0**  produces: **34:1:2.4/117:12:45.7**
**A0-B0-C0.0/X0-Y0-Z0.0** produces: **3412.4/117-1245.7**

Dashes work fine in MGRS.

We have an Web Page Help example in the WAB CT widget for formatting DMS with dashes and a slash between lat/lon.  I tried to replicate in the desktop addin, and can't get it to work.  Other characters like ":" or "+" work, but not "-".

**Comment by topowright** [comment]
Please give me an estimation on how much work would be needed to add special characters.

**Comment by topowright** [comment]
We will not use dashes in this coordinate type as separators due to the possible misunderstanding of a negative coordinate.
