### ISSUE TITLE
Point Flash Graphic

### ISSUE THREAD

**Issue by joebayles** [Esri/coordinate-tool-addin-dotnet#67]
The Flash Tool works great in identifying the point on the map (Red Star in ArcGIS Pro, Green Diamond in ArcMap).

Attempting to remove the graphic, however, is proving difficult. In ArcMap, I have to clear graphics from the Draw toolbar. In ArcGIS Pro, I can't seem to clear the graphic.

I would suggest either engineering the flash to clear itself automatically, or add a "Flash Clear" button.

This is a fresh install of the coordinate tool from today (February 19th, 2016).
ArcGIS Pro 1.2 (Build 5022)
ArcMap 10.4 Final (Build 5524)

**Comment by topowright** [comment]
After meeting with the customer we plan for the tool to not drop a graphic  #68

**Comment by joebayles** [comment]
Roger.
