### ISSUE TITLE
Decrease Size of the add-in when tool is docked

### ISSUE THREAD

**Issue by mcalamito** [Esri/coordinate-tool-addin-dotnet#69]
Customer Feedback from on-site visit on 18FEB2016. Multiple users docked their Coordinate Tool window underneath the Table of Contents. This was their initial workflow/instinct. Neither right or wrong, this is the location that they placed it. In doing so, the Table of Contents had to be expanded in order to see the full output of coordinates in their output list. This reduced the amount of room the user had in their analyst window (Data Frame window). 

If wanting to eliminate buttons, a few options could be to create Right-click options per Output row to allow the user to Configure and Delete/Remove the Coordinate Output. This would eliminate two buttons on the row. Buttons could also be combined into an over-arching settings button near the top of the Coordinate Tool window. There are numerous ways that this could be implemented, but just some ideas based on the users initial feedback regarding the buttons.
![coordinate tool_docked2](https://cloud.githubusercontent.com/assets/16350903/13232993/88723b8e-d97f-11e5-9b14-d4c160a2b7fe.jpg)

**Comment by topowright** [comment]
The add-in should not make the user have to expand the dock-able window to such an extent that they lose  major amount of real estate.

**Comment by jmccausland** [comment]
@topowright @pshowalter @mcalamito someone review and verify

**Comment by topowright** [comment]
I have verified this issue.
