### ISSUE TITLE
Have coordinate update as you move cursor over map vs. just clicking on map

### ISSUE THREAD

**Issue by jofraley** [Esri/coordinate-tool-addin-dotnet#7]

**Comment by mcalamito** [comment]
I agree with the above in that this should be considered for an enhancement in near future releases maybe. When demoed on-site, this was one of a few features in which they immediately asked if Coordinate Tool had. As the users mouse moves across the Data Frame, coordinates need to update (somewhere...whether that is in the current Input box or not). When the user clicks the Map Point Tool, it would "lock" in that coordinate, also Enabling the button as pressed in to show it is in use. When the user no longer wants to "lock" in that coordinate, they could re-click the Map Point Tool to disable it or show it as not pressed in. This type of functionality was present in the "old" MA and the customer made that clear.

**Comment by topowright** [comment]
@jmccausland  I feel like we now have this capability in the other add-ins. If so we need to update the coordinate tool with this capability.

**Comment by topowright** [comment]
@jmccausland I have checked the other tools and they do not do this, but this is something that the old tool did that will be expected of the new add-in.

**Comment by jmccausland** [comment]
@topowright please review and verify

**Comment by topowright** [comment]
This has been verified.
